/** Component-owned associations between existing hosts and their published part slots. */
export const partBindings: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  'tp-drag-drop-list': {
    ':host': 'drag-drop-list-root',
    '.list': 'drag-drop-list-list',
    '.item': 'drag-drop-list-item',
    '.handle': 'drag-drop-list-handle',
    '.empty': 'drag-drop-list-empty',
  },
  'tp-form': {
    form: 'form',
    'form > [slot="actions"]': 'form-actions',
    'form > [slot="error-summary"]': 'form-error-summary',
  },
  'tp-checkbox': {
    '.root': 'checkbox',
    '.indicator': 'checkbox-indicator',
  },
  'tp-button': {
    '.control': 'button',
    "[part~='button-leading-mark']": 'button-leading-mark',
    "[part~='button-trailing-mark']": 'button-trailing-mark',
  },
  'tp-tabs': {
    "[part='tabs']": 'tabs',
    "[part='tabs-list']": 'tabs-list',
  },
  'tp-alert': {
    '.alert': 'alert',
    '.title': 'alert-title',
  },
  'tp-badge': {
    '.badge': 'badge',
  },
  'tp-bubble': {
    '.bubble': 'bubble-root',
  },
  'tp-button-group': {
    "[part~='button-group']": 'button-group',
  },
  'tp-card': {
    '.card > header': 'card-header',
    '.card > .content': 'card-content',
    '.card > footer': 'card-footer',
  },
  'tp-empty-state': {
    '.root': 'empty-state',
    '.description': 'empty-state-description',
  },
  'tp-key-hint': {
    kbd: 'key-hint',
  },
  'tp-label': {
    '.optional': 'label-optional-indicator',
  },
  'tp-list-item-separator': { '.separator': 'list-item-separator' },
  'tp-list-item-group': { '.group': 'list-item' },
  'tp-list-item': {
    '.item': 'list-item-root',
    '.description': 'list-item-description',
    '.media': 'list-item-media',
    '.content': 'list-item-content',
    '.title': 'list-item-title',
    '.actions': 'list-item-actions',
    '.header': 'list-item-header',
    '.footer': 'list-item-footer',
  },
  'tp-message': {
    '.message': 'message-root',
    '.meta': 'message-header',
    '.avatar': 'message-avatar',
    '.content': 'message-content',
    '.footer': 'message-footer',
  },
  'tp-input': {
    input: 'input',
  },
  'tp-text-area': {
    textarea: 'text-area',
  },
  'tp-native-select': {
    '[part~="native-select"]': 'native-select',
    '[part~="native-select-control"]': 'native-select-control',
    '[part~="native-select-option-group"]': 'native-select-option-group',
    '[part~="native-select-option"]': 'native-select-option',
    '[part~="native-select-indicator"]': 'native-select-indicator',
  },
  'tp-slider': {
    '[part~="slider"]': 'slider',
    '[part~="slider-track"]': 'slider-track',
    '[part~="slider-range"]': 'slider-range',
    '[part~="slider-thumb"]': 'slider-thumb',
    '[part~="slider-label"]': 'slider-label',
    '[part~="slider-output"]': 'slider-output',
  },
  'tp-slider-thumb': {
    '[part~="slider-thumb"]': 'slider-thumb',
  },
  'tp-field': {
    "[part='field-legend']": 'field-legend',
    "[part='field-field-group']": 'field-field-group',
    "[part='field-field']": 'field-field',
    "[part='field-control-region']": 'field-control-region',
    "[part='field-title']": 'field-title',
    "[part='field-separator']": 'field-separator',
    "[part='field']": 'field',
    "[part='field-label']": 'field-label',
    "[part='field-description']": 'field-description',
    "[part='field-error']": 'field-error',
  },
  'tp-input-group': {
    "[part='input-group']": 'input-group',
    '.addon': 'input-group-addon',
  },
  'tp-calendar': {
    '.root': 'calendar',
    '.header': 'calendar-header',
    '.months': 'calendar-month-grid',
    '.day': 'calendar-day',
  },
  'tp-questionnaire': {
    form: 'questionnaire',
    fieldset: 'questionnaire-question',
    "[part='questionnaire-progress']": 'questionnaire-progress',
    "[part='questionnaire-title']": 'questionnaire-title',
    "[part='questionnaire-description']": 'questionnaire-description',
    "[part='questionnaire-choices']": 'questionnaire-choices',
    "[part='questionnaire-choice']": 'questionnaire-choice',
    "[part='questionnaire-error']": 'questionnaire-error',
    "[part='questionnaire-actions']": 'questionnaire-actions',
  },
  'tp-progress': {
    '[part~="progress"]': 'progress',
    '[part~="progress-label"]': 'progress-label',
    '[part~="progress-value-output"]': 'progress-value-output',
    '[part~="progress-track"]': 'progress-track',
    '[part~="progress-indicator"]': 'progress-indicator',
  },
  'tp-toast': {
    '.toast': 'toast-toast',
    '.content': 'toast-content',
    '[part="close focusable"]': 'toast-close',
  },
  'tp-navigation-panel': {
    '.panel': 'navigation-panel',
  },
  'tp-select': {
    '[part~="select-anchor"]': 'select-anchor',
    '[part~="select-input"]': 'select-input',
    '[part~="select-clear"]': 'select-clear',
    '[part~="select-chip-list"]': 'select-chip-list',
    '[part~="select-chip"]': 'select-chip',
    '[part~="select-chip-remove"]': 'select-chip-remove',
    '[part~="select-collection"]': 'select-collection',
    '[part~="select-empty-state"]': 'select-empty-state',
    '[part~="select-row"]': 'select-row',
    '[part~="select"]': 'select',
    '[part~="select-trigger"]': 'select-trigger',
    '[part~="select-value"]': 'select-value',
    '[part~="select-content"]': 'select-content',
    '[part~="select-list"]': 'select-list',
    '[part~="select-group"]': 'select-group',
    '[part~="select-label"]': 'select-label',
    '[part~="select-option"]': 'select-option',
    '[part~="select-separator"]': 'select-separator',
    '[part~="select-scroll-up-button"]': 'select-scroll-up-button',
    '[part~="select-scroll-down-button"]': 'select-scroll-down-button',
  },
  'tp-command-palette': {
    '[part~="command-palette"]': 'command-palette',
    '[part~="command-palette-input-wrapper"]': 'command-palette-input-wrapper',
    '[part~="command-palette-input"]': 'command-palette-input',
    '[part~="command-palette-list"]': 'command-palette-list',
    '[part~="command-palette-group"]': 'command-palette-group',
    '[part~="command-palette-item"]': 'command-palette-item',
    '[part~="command-palette-empty-state"]': 'command-palette-empty-state',
    '[part~="command-palette-separator"]': 'command-palette-separator',
    '[part~="command-palette-shortcut-hint"]': 'command-palette-shortcut-hint',
  },
  'tp-carousel': {
    '[part="previous focusable"]': 'carousel-previous',
    '[part="next focusable"]': 'carousel-next',
    '[part="root"]': 'carousel',
    '.viewport': 'carousel-viewport',
    '.track': 'carousel-track',
  },
  'tp-avatar': {
    ':host': 'avatar',
    img: 'avatar-image',
    "[part~='fallback']": 'avatar-fallback',
  },
  'tp-avatar-group': {
    '.group': 'avatar-group',
    '.count': 'avatar-overflow-count',
  },
  'tp-spinner': {
    ':host': 'spinner',
    '.visually-hidden': 'spinner-accessible-label',
  },
  // Navigation Panel projects its separator recipe onto the inherited root.
  'tp-navigation-panel-separator': {},
  'tp-separator': {
    ':host': 'separator',
  },
  'tp-marker': {
    '.root': 'marker',
    '.icon': 'marker-icon',
    '.content': 'marker-content',
  },
  'tp-skeleton': {
    "[part~='skeleton']": 'skeleton',
  },
  'tp-switch': {
    '.root': 'switch',
    '.thumb': 'switch-thumb',
  },
  'tp-otp-field': {
    '.root': 'one-time-code-field',
    '.group': 'one-time-code-field-group',
    '.slot': 'one-time-code-field-slot',
  },
};
