import { LitElement, html, nothing } from 'lit';
import type { TpValueChangeEvent } from '../../foundation/events.js';
import report from '../size-report.json';
import { kb, sizeChartRenderer, sizeChartSeries, type SizeChartRow } from './size-chart.js';
import './size-report.css';

type Component = (typeof report.components)[number];
type SortKey = 'documented' | 'root' | 'own' | 'name';

// Components ship from `@tweakpad/ui`, widgets from `@tweakpad/ui/widgets`; each section has its
// own whole-section total.
const sectionRows = (section: string) =>
  report.components.filter((component) => component.section === section);
const componentRows = sectionRows('components');
const widgetRows = sectionRows('widgets');
const share = (bytes: number, total: number) => `${((bytes / total) * 100).toFixed(1)}%`;
const sorters: Record<SortKey, (a: Component, b: Component) => number> = {
  documented: (a, b) => b.gzip - a.gzip,
  root: (a, b) => b.rootGzip - a.rootGzip,
  own: (a, b) => b.ownGzip - a.ownGzip,
  name: (a, b) => a.name.localeCompare(b.name),
};
const chartRows: SizeChartRow[] = [...componentRows]
  .sort(sorters.documented)
  .slice(0, 15)
  .map((component) => ({
    name: component.name,
    shared: report.shared.gzip,
    component: Math.max(0, component.gzip - report.shared.gzip),
  }));
const largest = [...componentRows].sort(sorters.documented)[0]!;
// Horizontal bars take their height from the row count, not the default 16:9 plot.
const chartPresentation = {
  'data-visualization-plot-region': { styleHook: { 'aspect-ratio': 'auto' } },
};

/**
 * The bundle size report (generated by `npm run size:report`), composed from library
 * components: Cards, Tabs, Data visualization with Tooltip, Input, Select, Table and Badges.
 */
export class SizeReportView extends LitElement {
  static override properties = { query: { state: true }, sort: { state: true } };
  query = '';
  sort: SortKey = 'documented';

  protected override createRenderRoot() {
    return this;
  }

  #filtered(rows: Component[]): Component[] {
    const query = this.query.trim().toLowerCase();
    return rows
      .filter(
        (component) =>
          !query ||
          component.name.toLowerCase().includes(query) ||
          component.tagName.includes(query) ||
          component.includes.some((tag) => tag.includes(query)),
      )
      .sort(sorters[this.sort]);
  }

  protected override render() {
    const rows = this.#filtered(componentRows);
    const widgets = this.#filtered(widgetRows);
    return html`<div class="size-report">
      <header class="size-report-header">
        <div>
          <h1>Bundle size</h1>
          <p>
            What an application ships for each component of <code>@tweakpad/ui</code>
            ${report.version}: the published files it imports, sized as the build log lists them,
            and gzipped.
          </p>
        </div>
        <div class="size-report-status">
          <tp-badge variant="outline">v${report.version}</tp-badge>
          <tp-badge>Tree-shaking verified</tp-badge>
        </div>
      </header>

      <section class="size-report-cards" aria-label="Summary">
        ${this.#card('Shared runtime', kb(report.shared.gzip), 'Paid once per application')}
        ${this.#card('lit', kb(report.lit.gzip), 'Peer dependency, not counted below')}
        ${this.#card('Whole library', kb(report.full.gzip), '@tweakpad/ui/register')}
        ${this.#card(
          'Largest component',
          kb(largest.gzip),
          `${largest.name}, ${share(largest.gzip, report.full.gzip)} of the library`,
        )}
        ${this.#card(
          'Widgets',
          kb(report.fullWidgets.gzip),
          `@tweakpad/ui/register/widgets, ${widgetRows.length} published`,
        )}
      </section>

      <tp-tabs default-value="overview" class="size-report-tabs">
        <button slot="tab" value="overview">Overview</button>
        <button slot="tab" value="components">All components (${componentRows.length})</button>
        <button slot="tab" value="widgets">Widgets (${widgetRows.length})</button>
        <button slot="tab" value="method">Method</button>

        <div slot="panel" value="overview">${this.#overview()}</div>
        <div slot="panel" value="components">
          ${this.#table(rows, componentRows.length, report.full.gzip, 'components')}
        </div>
        <div slot="panel" value="widgets">
          ${
            widgetRows.length
              ? this.#table(widgets, widgetRows.length, report.fullWidgets.gzip, 'widgets')
              : html`<tp-empty-state>
                  No widgets are published yet
                  <span slot="description"
                    >Each widget is measured from <code>@tweakpad/ui/widgets</code> as it lands; the
                    color picker is planned first.</span
                  >
                </tp-empty-state>`
          }
        </div>
        <div slot="panel" value="method">${this.#method()}</div>
      </tp-tabs>
    </div>`;
  }

  #card(title: string, value: string, description: string) {
    return html`<tp-card>
      <h2 slot="header">${title}</h2>
      <p slot="description">${description}</p>
      <p class="size-report-figure">${value}</p>
    </tp-card>`;
  }

  #overview() {
    return html`<tp-data-visualization
      class="size-report-chart"
      label="Largest components"
      description="The 15 largest components as documented, in gzip size. Striped segments are the shared runtime every component needs; solid segments are the component's own code and the parts it renders."
      .data=${chartRows}
      .series=${sizeChartSeries}
      .renderer=${sizeChartRenderer}
      .partPresentation=${chartPresentation}
      interaction="both"
    >
      <tp-table slot="table" label="Largest components">
        <table>
          <caption>
            Largest components (gzip)
          </caption>
          <thead>
            <tr>
              <th scope="col">Component</th>
              <th scope="col">Shared runtime</th>
              <th scope="col">Component</th>
            </tr>
          </thead>
          <tbody>
            ${chartRows.map(
              (row) =>
                html`<tr>
                  <th scope="row">${row.name}</th>
                  <td>${kb(row.shared)}</td>
                  <td>${kb(row.component)}</td>
                </tr>`,
            )}
          </tbody>
        </table>
      </tp-table>
    </tp-data-visualization>`;
  }

  #table(rows: Component[], count: number, total: number, noun: string) {
    return html`<div class="size-report-toolbar">
        <tp-input
          type="search"
          label="Filter components"
          placeholder="Filter by name, tag or dependency"
          no-autofill
          @tp-value-change=${(event: TpValueChangeEvent<string>) => {
            this.query = event.detail.value;
          }}
        ></tp-input>
        <tp-select
          label="Sort by"
          default-value="documented"
          @tp-value-change=${(event: TpValueChangeEvent<SortKey>) => {
            this.sort = event.detail.value;
          }}
        >
          <option value="documented">As documented</option>
          <option value="root">Root only</option>
          <option value="own">Beyond shared</option>
          <option value="name">Name</option>
        </tp-select>
      </div>
      <tp-table label="Component sizes" sticky-header sticky-start-columns="1">
        <table>
          <caption>
            ${rows.length} of ${count} ${noun}
          </caption>
          <thead>
            <tr>
              <th scope="col">Component</th>
              <th scope="col">As documented</th>
              <th scope="col">Shipped</th>
              <th scope="col">Root only</th>
              <th scope="col">Beyond shared</th>
              <th scope="col">Of section</th>
              <th scope="col">Modules</th>
              <th scope="col">Also ships</th>
            </tr>
          </thead>
          <tbody>
            ${rows.map((component) => this.#row(component, total))}
          </tbody>
        </table>
      </tp-table>`;
  }

  #row(component: Component, total: number) {
    return html`<tr>
      <th scope="row">
        <span class="size-report-name">${component.name}</span>
        <code>${component.tagName}</code>
        ${
          component.uses.length
            ? html`<span class="size-report-muted">with ${component.uses.join(', ')}</span>`
            : nothing
        }
      </th>
      <td class="size-report-number"><strong>${kb(component.gzip)}</strong></td>
      <td class="size-report-number">${kb(component.bytes)}</td>
      <td class="size-report-number">${kb(component.rootGzip)}</td>
      <td class="size-report-number">${kb(component.ownGzip)}</td>
      <td class="size-report-number">${share(component.gzip, total)}</td>
      <td class="size-report-number">${component.modules}</td>
      <td>
        ${
          component.includes.length
            ? html`<tp-tooltip
                ><tp-badge slot="trigger" variant="secondary" tabindex="0"
                  >${component.includes.length} elements</tp-badge
                >${component.includes.join(', ')}</tp-tooltip
              >`
            : html`<span class="size-report-muted">None</span>`
        }
      </td>
    </tr>`;
  }

  #method() {
    return html`<div class="size-report-method">
      <p>${report.method}</p>
      <ul>
        <li>
          <strong>As documented</strong>: the gzip size of the component with the parts its
          canonical example composes, for example the media player with its video layout.
        </li>
        <li>
          <strong>Shipped</strong>: the same files before compression, as <code>npm run build</code>
          lists them (kB of 1000 bytes). The build log's gzip column uses a different compressor and
          lands within about one percent of the figures here.
        </li>
        <li><strong>Root only</strong>: the element alone, without authored parts.</li>
        <li>
          <strong>Beyond shared</strong>: the documented size minus the shared runtime every
          component needs. Components share more than that runtime, so adding a second component
          usually costs less than this column.
        </li>
        <li>
          <strong>Tree-shaking</strong>: each component is also bundled from its own module. The
          report fails if importing through <code>@tweakpad/ui</code> ships any module the direct
          import does not.
        </li>
        <li>
          <strong>Widgets</strong>: measured the same way from <code>@tweakpad/ui/widgets</code>,
          with their own whole-section total. The report fails if
          <code>@tweakpad/ui/register</code> ships a widget module.
        </li>
      </ul>
      <p class="size-report-muted">
        Generated ${new Date(report.generatedAt).toLocaleString()}. Regenerate with
        <code>npm run size:report</code>.
      </p>
    </div>`;
  }
}

if (!customElements.get('size-report-view'))
  customElements.define('size-report-view', SizeReportView);
