import type { ColorPickerStrings } from './types.js';

export const DEFAULT_STRINGS: ColorPickerStrings = {
  red: 'Red',
  green: 'Green',
  blue: 'Blue',
  hue: 'Hue',
  saturation: 'Saturation',
  lightness: 'Lightness',
  value: 'Brightness',
  whiteness: 'Whiteness',
  blackness: 'Blackness',
  cyan: 'Cyan',
  magenta: 'Magenta',
  yellow: 'Yellow',
  key: 'Key (black)',
  a: 'Green–red (a)',
  b: 'Blue–yellow (b)',
  chroma: 'Chroma',
  alpha: 'Alpha',
  hex: 'Hex',
  format: 'Color format',
  areaGroup: 'Saturation and brightness',
  wheelGroup: 'Hue and saturation',
  triangleGroup: 'Saturation and brightness',
  harmony: 'Harmony',
  harmonyHandle: 'Harmony color',
  eyedropper: 'Pick a color from the screen',
  compare: 'Original and current color',
  original: 'Restore the original color',
  copy: 'Copy color',
  empty: 'none',
  generate: 'Generate schemes',
  template: 'Template',
  savedColors: 'Saved colors',
  recentColors: 'Recent colors',
  views: 'Color picker views',
  viewArea: 'Color picker',
  viewSliders: 'Sliders',
  viewWheel: 'Wheel',
  viewTriangle: 'Triangle',
  viewSwatches: 'Swatches',
  viewSchemes: 'Schemes',
  formatHex: 'Hex',
  formatRgb: 'RGB',
  formatHsl: 'HSL',
  formatHwb: 'HWB',
  formatHsv: 'HSV',
  formatLab: 'Lab',
  formatOklab: 'OKLab',
  formatOklch: 'OKLCH',
  formatCmyk: 'CMYK',
  harmonyNone: 'None',
  harmonyComplementary: 'Complementary',
  harmonyAnalogous: 'Analogous',
  harmonyTriad: 'Triad',
  harmonyCompound: 'Compound',
  harmonyCustom: 'Custom',
  schemeTints: 'Tints',
  schemeShades: 'Shades',
  schemeTones: 'Tones',
  schemeAnalogous: 'Analogous',
  schemeComplementary: 'Complementary',
  schemeTriad: 'Triad',
  schemeTetrad: 'Tetrad',
  valueMissing: 'Please choose a color.',
};

export function resolveStrings(overrides: Partial<ColorPickerStrings> = {}): ColorPickerStrings {
  return { ...DEFAULT_STRINGS, ...overrides };
}
