import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html } from 'lit';
import './size-report/size-report.js';

/**
 * Bundle size per catalog component, generated by `npm run size:report` into
 * `size-report.json`. Each row is what an application ships when it imports that component from
 * `@tweakpad/ui` and defines it.
 */
const meta = {
  title: 'Tweakpad UI/Bundle size',
  parameters: { layout: 'padded', controls: { disable: true } },
} satisfies Meta;

export default meta;
type Story = StoryObj;

export const Report: Story = {
  render: () => html`<size-report-view></size-report-view>`,
};
