import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html } from 'lit';
import report from './size-report.json';

/**
 * Bundle size per catalog component, generated by `npm run size:report`. Each row is what an
 * application ships when it imports that one component from `@tweakpad/ui` and defines it.
 */
const kb = (bytes: number) => `${(bytes / 1024).toFixed(1)} kB`;
const share = (bytes: number) => `${((bytes / report.full.gzip) * 100).toFixed(1)}%`;

const meta = {
  title: 'Tweakpad UI/Bundle size',
  parameters: { layout: 'padded', controls: { disable: true } },
} satisfies Meta;

export default meta;
type Story = StoryObj;

export const Report: Story = {
  render: () => html`
    <div style="display:grid;gap:var(--tp-space-6);max-inline-size:72rem">
      <div style="display:grid;gap:var(--tp-space-2)">
        <h1 style="margin:0;font-size:var(--tp-text-2xl)">Bundle size per component</h1>
        <p style="margin:0;color:var(--tp-muted-foreground)">
          ${report.method} Generated ${new Date(report.generatedAt).toLocaleString()} for version
          ${report.version}. <strong>As documented</strong> measures the component with the parts
          its canonical example composes (for example the media player with its video layout);
          <strong>Root only</strong> is the element alone. Tree-shaking is verified for both:
          importing through the package entry ships exactly the modules the components' own modules
          need.
        </p>
      </div>

      <tp-table label="Size summary">
        <tp-table-caption>Reference sizes (gzip)</tp-table-caption>
        <tp-table-header>
          <tp-table-row>
            <tp-table-head scope="col">Bundle</tp-table-head>
            <tp-table-head scope="col">Gzip</tp-table-head>
            <tp-table-head scope="col">Minified</tp-table-head>
            <tp-table-head scope="col">Meaning</tp-table-head>
          </tp-table-row>
        </tp-table-header>
        <tp-table-body>
          <tp-table-row>
            <tp-table-head scope="row">Shared runtime</tp-table-head>
            <tp-table-cell>${kb(report.shared.gzip)}</tp-table-cell>
            <tp-table-cell>${kb(report.shared.minified)}</tp-table-cell>
            <tp-table-cell>Code every component needs; paid once per application.</tp-table-cell>
          </tp-table-row>
          <tp-table-row>
            <tp-table-head scope="row">lit (peer dependency)</tp-table-head>
            <tp-table-cell>${kb(report.lit.gzip)}</tp-table-cell>
            <tp-table-cell>${kb(report.lit.minified)}</tp-table-cell>
            <tp-table-cell>Not included in the component sizes below.</tp-table-cell>
          </tp-table-row>
          <tp-table-row>
            <tp-table-head scope="row">Everything (register)</tp-table-head>
            <tp-table-cell>${kb(report.full.gzip)}</tp-table-cell>
            <tp-table-cell>${kb(report.full.minified)}</tp-table-cell>
            <tp-table-cell
              ><code>@tweakpad/ui/register</code>: every component defined.</tp-table-cell
            >
          </tp-table-row>
        </tp-table-body>
      </tp-table>

      <tp-table label="Component sizes" sticky-header sticky-start-columns="1">
        <tp-table-caption>Per component, largest first</tp-table-caption>
        <tp-table-header>
          <tp-table-row>
            <tp-table-head scope="col">Component</tp-table-head>
            <tp-table-head scope="col">As documented</tp-table-head>
            <tp-table-head scope="col">Root only</tp-table-head>
            <tp-table-head scope="col">Beyond shared</tp-table-head>
            <tp-table-head scope="col">Of everything</tp-table-head>
            <tp-table-head scope="col">Modules</tp-table-head>
            <tp-table-head scope="col">Also ships</tp-table-head>
          </tp-table-row>
        </tp-table-header>
        <tp-table-body>
          ${report.components.map(
            (component) => html`
              <tp-table-row>
                <tp-table-head scope="row">
                  ${component.name}<br /><code>${component.tagName}</code>
                  ${
                    component.uses.length
                      ? html`<br /><small style="color:var(--tp-muted-foreground)"
                            >with ${component.uses.join(', ')}</small
                          >`
                      : ''
                  }
                </tp-table-head>
                <tp-table-cell>${kb(component.gzip)}</tp-table-cell>
                <tp-table-cell>${kb(component.rootGzip)}</tp-table-cell>
                <tp-table-cell>${kb(component.ownGzip)}</tp-table-cell>
                <tp-table-cell>${share(component.gzip)}</tp-table-cell>
                <tp-table-cell>${component.modules}</tp-table-cell>
                <tp-table-cell>
                  ${
                    component.includes.length
                      ? html`<span style="display:flex;flex-wrap:wrap;gap:var(--tp-space-1)"
                          >${component.includes.map(
                            (tag) => html`<tp-badge variant="outline">${tag}</tp-badge>`,
                          )}</span
                        >`
                      : '—'
                  }
                </tp-table-cell>
              </tp-table-row>
            `,
          )}
        </tp-table-body>
      </tp-table>
    </div>
  `,
};
