import type { ComponentDefinition } from '../definition.js';
import { definePresentation } from '../family.js';
import { timelineAppearance } from '../recipes/timeline.js';

const definition: ComponentDefinition = {
  name: 'Timeline',
  tagName: 'tp-timeline',
  kind: 'compound-reexport',
  sourceNode: 'ucl21-timeline',
  axes: [
    { name: 'orientation', values: ['vertical', 'horizontal', 'responsive'], default: 'vertical' },
    { name: 'align', values: ['start', 'end', 'alternate', 'alternate-reverse'], default: 'end' },
  ],
  parts: [
    {
      name: 'timeline',
      publicName: 'Root',
      presentationKeys: [
        'timeline',
        'timeline-orientation-vertical',
        'timeline-orientation-horizontal',
        'timeline-orientation-responsive',
        'timeline-align-start',
        'timeline-align-end',
        'timeline-align-alternate',
        'timeline-align-alternate-reverse',
      ],
      cardinality: 'exactly one public owner host per control instance',
    },
    {
      name: 'timeline-item',
      publicName: 'Item',
      presentationKeys: [
        'timeline-item',
        'timeline-item-orientation-vertical',
        'timeline-item-orientation-horizontal',
        'timeline-item-orientation-responsive',
        'timeline-item-align-start',
        'timeline-item-align-end',
        'timeline-item-align-alternate',
        'timeline-item-align-alternate-reverse',
      ],
      cardinality: 'zero or more element children of Root',
    },
    {
      name: 'timeline-item-marker',
      publicName: 'Marker',
      presentationKeys: [
        'timeline-item-marker',
        'timeline-item-marker-orientation-vertical',
        'timeline-item-marker-orientation-horizontal',
        'timeline-item-marker-orientation-responsive',
        'timeline-item-marker-align-start',
        'timeline-item-marker-align-end',
        'timeline-item-marker-align-alternate',
        'timeline-item-marker-align-alternate-reverse',
      ],
      cardinality: 'exactly one in each Item',
    },
    {
      name: 'timeline-item-dot',
      publicName: 'Dot',
      presentationKeys: [
        'timeline-item-dot',
        'timeline-item-dot-orientation-vertical',
        'timeline-item-dot-orientation-horizontal',
        'timeline-item-dot-orientation-responsive',
        'timeline-item-dot-align-start',
        'timeline-item-dot-align-end',
        'timeline-item-dot-align-alternate',
        'timeline-item-dot-align-alternate-reverse',
      ],
      cardinality: 'zero or one in each Marker; present when no marker content is supplied',
    },
    {
      name: 'timeline-item-connector-before',
      publicName: 'Before connector',
      presentationKeys: [
        'timeline-item-connector-before',
        'timeline-item-connector-before-orientation-vertical',
        'timeline-item-connector-before-orientation-horizontal',
        'timeline-item-connector-before-orientation-responsive',
        'timeline-item-connector-before-align-start',
        'timeline-item-connector-before-align-end',
        'timeline-item-connector-before-align-alternate',
        'timeline-item-connector-before-align-alternate-reverse',
      ],
      cardinality: 'exactly one in each Item; hidden on the first Item',
    },
    {
      name: 'timeline-item-connector-after',
      publicName: 'After connector',
      presentationKeys: [
        'timeline-item-connector-after',
        'timeline-item-connector-after-orientation-vertical',
        'timeline-item-connector-after-orientation-horizontal',
        'timeline-item-connector-after-orientation-responsive',
        'timeline-item-connector-after-align-start',
        'timeline-item-connector-after-align-end',
        'timeline-item-connector-after-align-alternate',
        'timeline-item-connector-after-align-alternate-reverse',
      ],
      cardinality: 'exactly one in each Item; hidden on the last Item',
    },
    {
      name: 'timeline-item-connector-fill',
      publicName: 'Fill',
      presentationKeys: [
        'timeline-item-connector-fill',
        'timeline-item-connector-fill-orientation-vertical',
        'timeline-item-connector-fill-orientation-horizontal',
        'timeline-item-connector-fill-orientation-responsive',
        'timeline-item-connector-fill-align-start',
        'timeline-item-connector-fill-align-end',
        'timeline-item-connector-fill-align-alternate',
        'timeline-item-connector-fill-align-alternate-reverse',
      ],
      cardinality: 'exactly one in each connector',
    },
    {
      name: 'timeline-item-content',
      publicName: 'Content',
      presentationKeys: [
        'timeline-item-content',
        'timeline-item-content-orientation-vertical',
        'timeline-item-content-orientation-horizontal',
        'timeline-item-content-orientation-responsive',
        'timeline-item-content-align-start',
        'timeline-item-content-align-end',
        'timeline-item-content-align-alternate',
        'timeline-item-content-align-alternate-reverse',
      ],
      cardinality: 'exactly one in each Item',
    },
    {
      name: 'timeline-item-opposite',
      publicName: 'Opposite',
      presentationKeys: [
        'timeline-item-opposite',
        'timeline-item-opposite-orientation-vertical',
        'timeline-item-opposite-orientation-horizontal',
        'timeline-item-opposite-orientation-responsive',
        'timeline-item-opposite-align-start',
        'timeline-item-opposite-align-end',
        'timeline-item-opposite-align-alternate',
        'timeline-item-opposite-align-alternate-reverse',
      ],
      cardinality: 'zero or one in each Item; present when opposite content is supplied',
    },
  ],
  nonVisualParts: ['status text'],
  motionRoles: [
    {
      name: 'connector',
      target: 'timeline-item-connector-fill',
      kind: 'state',
      phases: ['change'],
      completion: 'non-blocking',
      context: ['status', 'index', 'connector'],
    },
  ],
};

/** Timeline paints no surface; the Dot and Fill carry status (CL Timeline `tll-presentation`). */
export const timelinePresentation = definePresentation({
  definition,
  sources: [timelineAppearance],
  complete: true,
});
